### PR TITLE
Send binary from client to server

### PR DESCRIPTION
**Pull request by floryst**
Clients can send binary attachments to the server, much like how the server can send binary attachments to the client.

### CODE REVIEW

**Comment by jourdain** [comment]
LGTM, what do you think @aron-helser ?

**Comment by aronhelser** [comment]
yes, looks fine, as far as i can tell. We need to update travis keys?

**Comment by jourdain** [comment]
It seems that some test are failing.

**Comment by jourdain** [comment]
I've updated the tokens...

**Comment by floryst** [comment]
I think it's a python 3 test that's failing. I will make a change to fix it.

**Comment by floryst** [comment]
Tests have been resolved.

**Comment by aronhelser** [comment]
Why didn't we merge this? Should we merge now?

**Comment by floryst** [comment]
This should be mergable now.

**Pull request merged**
