### PR TITLE
fix(dependencies): update webpack for security updates.

### PR DESCRIPTION
**Pull request by aronhelser**
@jourdain does the webpack config look ok? It works for me....

### CODE REVIEW

**Comment by jourdain** [comment]
I think so. Do we load some css?

**Comment by aronhelser** [comment]
No, wslink doesn't use any CSS at all, even in the examples.

**Comment by jourdain** [comment]
So maybe you can drop the css-loader. And what about the `html-webpack-plugin` or the `webpack-dev-server`

**Comment by aronhelser** [comment]
ah, right! the others are used in the example and test build.

**Pull request merged**
