### PR TITLE
fix(launcher.py): Don't enforce begin/end marks in sanitize regexp

### PR DESCRIPTION
**Pull request by aronhelser**
Allow JS/C++ comments in launcher config. Add comments and sample
of sanitize config. Add test config used to tests/ dir.

CC @jourdain

### CODE REVIEW

**Comment by jourdain** [comment]
Is there a way to print that sample config that is part of the code? (in launcher.py)

**Comment by jourdain** [comment]
Love the fact you can keep the comments...

**Comment by aronhelser** [comment]
yes, just provide an invalid command line

**Comment by jourdain** [comment]
the -h should show it too.

**Comment by aronhelser** [comment]
Yes, we might want to use the comment-stripper a few more places...

**Comment by aronhelser** [comment]
Added sample config to -h output.

**Comment by jourdain** [comment]
LGTM, thanks for the changes.

**Pull request merged**
